- name: Replace Placeholder Images
  run: python .github/scripts/placeholder_image_replacer.py
  env:
    CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
    CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}