name: Generate Articles

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-articles:
    runs-on: ubuntu-latest
    
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-genai pillow requests markdown pyyaml numpy scikit-learn nltk
          
      - name: Replace Placeholder Images
        run: python .github/scripts/placeholder_image_replacer.py
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
      - name: Commit generated articles and data files
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add generated-articles/
          git add data/
          git add .last_keyword_index
          git commit -m "Auto-generate articles and update tracking data [skip ci]" || echo "No changes to commit"
          git push